# Generated by Django 4.2.11 on 2026-03-15 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gratuito', 'Gratuito'), ('basico', 'Básico'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('limite_imoveis', models.IntegerField(default=5)),
                ('limite_contratos', models.IntegerField(default=3)),
                ('vitrine_propria', models.BooleanField(default=False)),
                ('marketplace', models.BooleanField(default=False)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'planos',
            },
        ),
        migrations.CreateModel(
            name='PerfilImobiliaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imobiliarias/logos/')),
                ('telefone_publico', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email_publico', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_imobiliaria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil da Imobiliária',
                'verbose_name_plural': 'Perfis das Imobiliárias',
                'db_table': 'perfis_imobiliaria',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.plano'),
        ),
    ]
