# Generated by Django 4.2.11 on 2026-03-15 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
        ('imoveis', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inquilinos.inquilino'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anexo',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to=settings.AUTH_USER_MODEL),
        ),
    ]
