# Generated by Django 4.2.11 on 2026-03-15 16:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_aceita_pets_imovel_andares_imovel_banheiros_and_more'),
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo', models.CharField(choices=[('contato', 'Contato'), ('visita', 'Agendamento de Visita'), ('proposta', 'Proposta')], max_length=20)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data_visita', models.DateTimeField(blank=True, null=True)),
                ('valor_proposta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_atendimento', 'Em Atendimento'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
