# Generated by Django 4.2.11 on 2026-03-15 00:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('comercial', 'Comercial'), ('terreno', 'Terreno'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('em_manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'db_table': 'imoveis',
            },
        ),
    ]
