# Generated by Django 4.2.11 on 2026-03-15 16:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='aceita_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='andares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='banheiros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('aluguel', 'Aluguel'), ('venda', 'Venda'), ('ambos', 'Aluguel e Venda')], default='aluguel', max_length=10),
        ),
        migrations.AddField(
            model_name='imovel',
            name='mobiliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='suites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_academia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_churrasqueira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_piscina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_portaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_condominio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_iptu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('vendido', 'Vendido'), ('em_manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20),
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('arquivo', models.ImageField(upload_to='imoveis/fotos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('comodo', models.CharField(choices=[('sala', 'Sala'), ('cozinha', 'Cozinha'), ('quarto', 'Quarto'), ('suite', 'Suíte'), ('banheiro', 'Banheiro'), ('area_servico', 'Área de Serviço'), ('varanda', 'Varanda'), ('garagem', 'Garagem'), ('fachada', 'Fachada'), ('area_comum', 'Área Comum'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('capa', models.BooleanField(default=False)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Foto do Imóvel',
                'verbose_name_plural': 'Fotos dos Imóveis',
                'db_table': 'fotos_imovel',
                'ordering': ['ordem', 'created_at'],
            },
        ),
    ]
