# Generated by Django 4.2.11 on 2026-03-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_aceita_pets_imovel_andares_imovel_banheiros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='prox_metro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_ar_condicionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_deposito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_elevador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_lavanderia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tem_sacada',
            field=models.BooleanField(default=False),
        ),
    ]
