# Generated by Django 4.2.11 on 2026-03-15 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquilino_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
